### ISSUE TITLE
Please stop rebranding every week

### ISSUE THREAD

**Issue by amiranvarov** [souporserious/renoun#188]

**Comment by amiranvarov** [comment]
Hey, i like what you do, but it's a bit annoying when tool that you know keeps changing it's name every week

**Comment by noxify** [comment]
@souporserious explained it here why it was necessary:

https://github.com/souporserious/renoun/pull/184#issuecomment-2359013057

**Comment by souporserious** [comment]
@amiranvarov that wasn't my intention, I made a mistake with the original rename and want to make sure the project is sustainable for the future to avoid any other renaming. I understand it can be frustrating, feel free to support this free library [here](https://github.com/sponsors/souporserious).
