### ISSUE TITLE
How can I add more languages to the CodeBlock

### ISSUE THREAD

**Issue by ozgurozalp** [souporserious/renoun#228]
I can't use some languages ​​and I couldn't find how to add them in the documentation. Can you help me?

**Comment by noxify** [comment]
Hi,

Which version are you using? 

Based on the code, you should be able to add/override the languages for the codeblock via the `<project-root>/renoun.json` with the latest renoun version.

Haven't tested it, but based on the code, it should work.

Ref: https://github.com/souporserious/renoun/blob/main/packages/renoun/src/utils/load-config.ts

**Comment by ozgurozalp** [comment]
Thank you, I solved my problem with this!

**Comment by ozgurozalp** [comment]
@noxify Yep! I looked at the source code. thx again

**Comment by souporserious** [comment]
Sorry some things are still in flux, the documentation will be better around this soon! Also need to get search working which should help surface this. Please see the [configuration](https://www.renoun.dev/docs/configuration#languages) page for now.
